export const documentTheme = {
  accessTitleBackground: '#af7a7a',
  accessSaveBackground: '#4a2727',
  doclinkDetailColor: '#666',
  doclinkDetailFontSize: '80%',
  doclinkDetailMargin: '0 0 0 8px',
  doclinkRemoveIconColor: '#6f6f6f',
  doclinkRemoveIconFontSize: '0.9rem',
  doclinkRemoveIconHoverColor: '#555',
  documentAccessHighColor: '#0aa3c2',
  documentWidgetHeight: '22rem',
  documentTitleHeight: '2rem',
  noDocumentColor: '#999',
  explorerBackground: '#ebfcff',
  explorerDateFontSize: '0.8rem',
  explorerDateColor: '#30596188',
  explorerSelectedBackground: '#e0d1af',
  explorerTitleBackground: '#0aa3c2',
  explorerTitleSubBg: '#98efff',
  explorerTitleColor: '#303844',
  explorerUploadBackground: '#1ba2c547',
  privateColor: '#777',
  selectedDocumentColor: '#6176a9',
  sharedColor: '#c3685e',
}
