export const editorTheme = {
  editorMargin: '5mm',
  editorParagraphsLineHeight: '1.2rem',
  editorParagraphsMargin: '1.2rem 2rem',
  editorH1Weight: 'bold',
  editorH1FontSize: '1.2rem',
  editorH1Margin: '2.5rem 2rem',
  editorH2Weight: 'bold',
  editorH2FontSize: '1rem',
  editorH2Margin: '2.5rem 2rem',
  editorH3Weight: 'bold',
  editorH3FontSize: '1rem',
  editorH3Margin: '2.5rem 2rem',
  editorPTextAlign: 'justify',
  editorHeaderEmBorderBottom: '1px solid #777',
  editorTitleFontSize: '2rem',
  editorTitleColor: '#333',
  editorTitlePadding: '0.5rem 0',
  editorTitleBorderBottom: '1px solid #eee',
  editorEmptyBorderLeft: '3px solid #e5e5e5',
  editorEmptyBefore: 'attr(data-placeholder)',
  editorEmptyBeforeOpacity: '0.3',
}
