export const chatTheme = {
  chatAuthorColor: '#999',
  chatDateBottom: '-16px',
  chatDateRight: '4px',
  chatDateColor: '#bbb',
  chatDateFontSize: '0.7rem',
  chatDateFontStyle: 'italic',
  // not a css thing.
  chatExplorerSmallTitleLimit: 7,
  chatExplorerSmallWidth: '35%',
  chatIconFontSize: '1.4rem',
  chatIconColor: '#888',
  chatMoreIconFontSize: '1rem',
  chatInputBackground: 'var(--chatMessageMeBackground)',
  chatLineHeight: '1.2rem',
  // TODO: Cleanup contactsXXX things if not needed
  contactsTitleBackground: '#c5a11b',
  contactsTitleSubBg: '#ffe595',
  contactsTitleColor: '#303844',
  contactsSelectedBackground: '#efdc82',
  contactsWidgetBackground: '#fff6eb',
  contactsWidgetBorderLeft: '1px solid #5f5f5f',
  chatMessageExtraColor: '#aaa',
  chatMessageFontSize: '0.9rem',
  chatMessageMeBackground: '#f7f1d4',
  chatMessageBackground: '#f3f3f3',
  chatMessageMeMargin: '0.2rem 0.5rem 1.4rem 1.4rem',
  chatMessageMePadding: '0.6rem 0.6rem 0.3rem',
  chatMessageMargin: '0.2rem 1.4rem 1.4rem 0.5rem',
  chatMessageBorder: '1px solid #aaa',
  chatMessagePadding: '0.3rem 0.6rem',
  userIconColor: '#444',
  userNameColor: '#444',
  userMeIconColor: '#444',
  userMeNameColor: '#666',
}
